#!/bin/bash
LHOST=$(ip -4 addr show dev tun0 | grep -oP 'inet \K[\d.]+')
RHOST=$(cat ~/.config/bin/target)

printf "export RHOST=%s\nexport LHOST=%s\n" "$RHOST" "$LHOST" > target.env
echo "[+] Created target.env"
