user_pref("network.proxy.allow_hijacking_localhost", true);
user_pref("ui.key.menuAccessKeyFocuses", false);
user_pref("devtools.editor.keymap", "vim");
user_pref("devtools.everOpened", true);
user_pref("devtools.selfxss.count", 5);
user_pref("devtools.toolbox.selectedTool", "webconsole");
user_pref("devtools.webconsole.input.editor", true);
user_pref("devtools.webconsole.input.editorOnboarding", false);
user_pref("devtools.webconsole.input.editorWidth", 930);
